### ISSUE TITLE
Bug: Using proxies leads to exception

### ISSUE THREAD

**Issue by jeffj1** [Protoprize/db-launcher-tool#1]
Thanks for the launcher, it works without proxies. But botting with proxies is the norm. When using proxies, the following exception is found:

`2023-12-23 23:16:40 [INFO] Successfully set initial world to 500!
2023-12-23 23:16:44 [ERROR] javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1446)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1417)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:219)
2023-12-23 23:16:44 [ERROR] 	at ap.ar(Unknown Source)
2023-12-23 23:16:44 [ERROR] 	at ap.ao(Unknown Source)
2023-12-23 23:16:44 [ERROR] 	at ai.call(Unknown Source)
2023-12-23 23:16:44 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2023-12-23 23:16:44 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2023-12-23 23:16:44 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-12-23 23:16:44 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1583)
2023-12-23 23:16:44 [ERROR] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.validator.Validator.validate(Validator.java:256)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)
2023-12-23 23:16:44 [ERROR] 	... 23 more
2023-12-23 23:16:44 [ERROR] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
2023-12-23 23:16:44 [ERROR] 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
2023-12-23 23:16:44 [ERROR] 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383)
2023-12-23 23:16:44 [ERROR] 	... 28 more`

**Comment by Protoprize** [comment]
This is not an issue related to this project. Plausible causes are probably the jagex launcher, dreambot or the proxies themselves.
